name: offline_web_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_w_log: ^0.0.8

  path_provider: ">=2.0.0 <3.0.0"
  path: ">=1.0.0 <2.0.0"
  webview_flutter: ">=3.0.0 <4.0.0"

  archive: ">=3.0.0 <4.0.0"

  shelf: ">=1.0.0 <2.0.0"
  shelf_static: ">=1.0.0 <2.0.0"
  # shelf_proxy: ">=1.0.0 <2.0.0"
  # shelf_router: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vue_demo.zip
